version: '3.8'

services:
  nowait-local-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: nowait
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT}:3306"
