version: '3.8'
name: nowait

services:
  nowait-local-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: nowait
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    ports:
      - "3307:3306"

  nowait-test-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: nowait_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
