spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/nowait
    username: user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: true

payment:
  deposit-payment-wait-minutes: 5
  approval-wait-minutes: 5
  toss-pay:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    confirm-url: https://api.tosspayments.com/v1/payments/confirm
