spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nowait;MODE=MySQL;
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

payment:
  kakao-pay:
    cid: TC0ONETIME
    secretKey: ${KAKAO_PAY_SECRET_KEY}
    readyRequestUrl: https://open-api.kakaopay.com/online/v1/payment/ready
    approvalUrl: ${KAKAO_PAY_APPROVAL_URL}
    cancelUrl: ${KAKAO_PAY_CANCEL_URL}
    failUrl: ${KAKAO_PAY_FAIL_URL}
