spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/nowait
    username: user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: true

payment:
  kakao-pay:
    cid: TC0ONETIME
    secretKey: ${KAKAO_PAY_SECRET_KEY}
    readyRequestUrl: https://open-api.kakaopay.com/online/v1/payment/ready
    approveRequestUrl: https://open-api.kakaopay.com/online/v1/payment/approve
    approvalUrl: ${KAKAO_PAY_APPROVAL_URL}
    cancelUrl: ${KAKAO_PAY_CANCEL_URL}
    failUrl: ${KAKAO_PAY_FAIL_URL}
